name: scan_push
on:
  workflow_run:
    workflows: ["build_test"]
    types: ["completed"]
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: write 
  id-token: write 
concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true
env:
  ECR_REPO: ${{vars.ECR_REPO}}
  ECR_REG: ${{vars.ECR_REG}}

jobs:
  scan:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{steps.tag.outputs.image_tag}}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: login to amazon 
        uses: aws-actions/configure-aws-credentials@v5
        with: 
          role-to-assume: ${{secrets.ROLE}}
          aws-region: ${{vars.REGION}}
      - name: download actifact from s3 
        run: aws s3 cp s3://felix-aws-bukcet-stores/image.tar .
      - name: download tags
        run: aws s3 cp s3://felix-aws-bukcet-stores/tag.txt .
      - name: load tag 
        id: tag
        run: echo "image_tag=$(cat tag.txt)" >> "$GITHUB_OUTPUT"
      - name: load image 
        run: docker load -i image.tar
      - name: check image 
        run: docker images 
      - name: run scan 
        uses: aquasecurity/trivy-action@0.33.0
        with: 
          image-ref: ${{steps.tag.outputs.image_tag}}
          format: table 
          vuln-type: 'os,library'
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL

  #=============
  #push
  #============

  push: 
    needs: scan 
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: login to amazon 
        uses: aws-actions/configure-aws-credentials@v5
        with: 
          role-to-assume: ${{secrets.ROLE}}
          aws-region: ${{vars.REGION}}
      - name: download actifact from s3 
        run: aws s3 cp s3://felix-aws-bukcet-stores/image.tar .
      - name: load to runner 
        run: docker load -i image.tar
      - name: check images
        run: docker images 
      - name: ecr login 
        uses: aws-actions/amazon-ecr-login@v2
      - name: push images
        run: | 
          docker tag ${{needs.scan.outputs.image-tag}} ${{env.ECR_REG}}${{env.ECR_REPO}}:latest
          docker push ${{env.ECR_REG}}${{env.ECR_REPO}}:latest
          docker push ${{needs.scan.outputs.image-tag}}
      - name: send email notification
        run: |
          aws sns publish \
          --topic-arn ${{secrets.ARN}} \
          --subject "pipline triggered" \
          --message "The pipline ran successfully and an image with ID : ${{needs.scan.outputs.image-tag}} was created" \
